#!/bin/bash

~/llvm/build-0309-gold/bin/clang++ $@ -target aarch64 \
  --sysroot ~/local/linaro/aarch64/sysroot-glibc-linaro-2.23-2017.02-aarch64-linux-gnu/ \
  -I/home/pyyou/local/linaro/aarch64/gcc-linaro-6.3.1-2017.02-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/include/c++/6.3.1/ \
  -I/home/pyyou/local/linaro/aarch64/gcc-linaro-6.3.1-2017.02-x86_64_aarch64-linux-gnu/aarch64-linux-gnu/include/c++/6.3.1/aarch64-linux-gnu/
